"""Browser UI for the private Friday administration dashboard."""

PAGE = r"""<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Friday Dashboard</title><style>
:root{color-scheme:dark;--bg:#090d19;--panel:#111a2d;--line:#2a3858;--text:#f2f6ff;--muted:#a6b4cf;--blue:#72a4ff;--green:#55dca0;--red:#ff8398}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 12% -10%,#203965 0,var(--bg) 42%);color:var(--text);font:14px Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1440px;margin:auto;padding:34px}.eyebrow{color:var(--blue);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{font-size:32px;margin:7px 0}h2{font-size:20px;margin:34px 0 13px}.muted{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:12px}.card,.panel{background:linear-gradient(145deg,#17233d,#10172a);border:1px solid var(--line);border-radius:14px}.card{padding:16px}.number{font-size:28px;font-weight:800;margin-bottom:4px}.panel{padding:20px}.split{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(320px,.8fr);gap:16px}.head{display:flex;align-items:center;justify-content:space-between;gap:12px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.wide{grid-column:1/-1}label{display:block;font-size:12px;font-weight:700;color:#cbd8f3;margin-bottom:5px}input,select,button{font:inherit;border:1px solid #3b4c70;border-radius:8px;background:#0b1324;color:var(--text);padding:10px}input{width:100%}button{cursor:pointer;font-weight:750;background:#2e67d9;border-color:#5387f0}button.secondary{background:transparent;border-color:#4a5f88}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.toggle input{width:auto;margin-right:7px}.pill{border:1px solid #455a82;border-radius:99px;padding:5px 9px;font-size:12px;white-space:nowrap}.ok{color:var(--green);border-color:#277c59}.bad{color:var(--red);border-color:#994154}.codebox{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#090f1d;border:1px solid #34476b;border-radius:8px;padding:10px;overflow-wrap:anywhere}.steps{padding-left:20px;line-height:1.8;color:var(--muted)}.steps b{color:var(--text)}table{width:100%;border-collapse:collapse;background:#10182a;border:1px solid var(--line);border-radius:12px;overflow:hidden}th,td{padding:10px;border-bottom:1px solid #2a3855;text-align:left;vertical-align:top}th{font-size:12px;color:#bdcce8}.scroll{overflow-x:auto}.small{font-size:12px}.secret-state{display:flex;gap:6px;flex-wrap:wrap}.secret-state span{font-size:11px;border:1px solid #425578;border-radius:99px;padding:4px 7px}@media(max-width:820px){main{padding:18px}.split,.form-grid{grid-template-columns:1fr}h1{font-size:26px}}
</style></head><body><main>
<div class="eyebrow">Friday · Operations Console</div><h1>Friday Dashboard</h1><p class="muted">Cấu hình transport, theo dõi phiên chạy và audit log. Credential chỉ ghi vào private runtime volume, không đọc ngược qua UI.</p>
<div class="cards" id="cards"></div>

<h2>Facebook Messenger</h2><div class="split"><section class="panel"><div class="head"><div><b>Kết nối Facebook Page</b><div class="muted small">Friday Facebook adapter đọc cấu hình mới ngay sau khi lưu.</div></div><span id="facebook-state" class="pill">Checking…</span></div><form id="facebook" class="form-grid"><div class="wide"><label class="toggle"><input type="checkbox" name="enabled"> Bật Facebook Page agent</label></div><div><label>Page name</label><input name="page_name" placeholder="Friday Page"></div><div><label>Facebook Page ID</label><input name="page_id" inputmode="numeric" placeholder="123456789"></div><div><label>Meta App ID</label><input name="app_id" placeholder="Meta App ID"></div><div><label>Graph API version</label><input name="graph_version" placeholder="v24.0"></div><div class="wide"><label>Public webhook URL</label><input name="webhook_url" placeholder="https://snakersdoo.io.vn/facebook/webhook"></div><div><label>App Secret</label><input name="app_secret" type="password" placeholder="Để trống để giữ secret đã lưu"></div><div><label>Page Access Token</label><input name="page_access_token" type="password" placeholder="Để trống để giữ token đã lưu"></div><div class="wide"><label>Webhook Verify Token</label><div class="row"><input name="verify_token" type="password" placeholder="Generate hoặc dán token bí mật"><button class="secondary" type="button" id="generate-token">Generate</button><button class="secondary" type="button" id="copy-token">Copy</button></div></div><div class="wide row"><button>Lưu cấu hình</button><button class="secondary" type="button" id="test-facebook">Test Graph API</button><span id="facebook-note" class="muted"></span></div></form></section><aside class="panel"><b>Webhook setup</b><ol class="steps"><li>Lưu Page credential trong form.</li><li>Copy callback URL này vào Meta Messenger API Setup.</li><li>Dán đúng Verify Token vừa tạo/lưu, sau đó chọn <b>Verify and save</b>.</li><li>Subscribe Page event <b>messages</b>.</li></ol><label>Callback URL</label><div class="row"><code id="callback-url" class="codebox">—</code><button class="secondary" type="button" id="copy-url">Copy</button></div><p class="muted small">Token chỉ hiển thị tại thời điểm tạo/nhập. Sau Save, Dashboard chỉ xác nhận token có tồn tại.</p><div id="secret-state" class="secret-state"></div></aside></div>

<section class="panel" style="margin-top:16px"><div class="head"><div><b>Facebook activity</b><div class="muted small">Chỉ metadata vận hành, không log nội dung tin nhắn Page.</div></div><div id="facebook-counts" class="muted small"></div></div><div class="scroll"><table><thead><tr><th>Time</th><th>Event</th><th>Sender / session</th><th>Result</th></tr></thead><tbody id="facebook-events"></tbody></table></div></section>

<h2>Users</h2><div class="row"><input id="user" placeholder="Filter user" style="max-width:260px"><select id="engine"><option value="">All engines</option><option value="claude">Claude</option><option value="codex">Codex</option></select></div><div class="scroll"><table><thead><tr><th>User</th><th>Status</th><th>Current engine</th><th>Runs</th><th>Failed</th><th>Permissions</th><th>Last seen</th></tr></thead><tbody id="users"></tbody></table></div>
<h2>All activity</h2><div class="scroll"><table><thead><tr><th>Time</th><th>User</th><th>Event</th><th>Engine / model</th><th>Session</th><th>Duration</th></tr></thead><tbody id="events"></tbody></table></div>
</main><script>
let dashboard,facebook;const $=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),ms=x=>x?`${(x/60000).toFixed(1)} min`:'0 min',label=x=>x==='chatgpt'?'Codex':x,time=x=>x?new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(x)):'—';const note=t=>$('#facebook-note').textContent=t;const copy=t=>navigator.clipboard.writeText(t).then(()=>note('Copied.')).catch(()=>note('Không copy được; hãy tự chọn và copy.'));
async function loadFacebook(){facebook=await fetch('/api/facebook/config').then(r=>r.json());let f=$('#facebook');for(let key of ['page_name','page_id','app_id','graph_version','webhook_url'])f.elements[key].value=facebook[key]||'';f.elements.enabled.checked=!!facebook.enabled;$('#callback-url').textContent=facebook.webhook_url||'—';let ready=facebook.configured;$('#facebook-state').textContent=ready?'Configured':'Needs configuration';$('#facebook-state').className=`pill ${ready?'ok':'bad'}`;$('#secret-state').innerHTML=[['App Secret',facebook.has_app_secret],['Verify Token',facebook.has_verify_token],['Page Token',facebook.has_page_access_token]].map(([n,v])=>`<span class='${v?'ok':'bad'}'>${esc(n)}: ${v?'saved':'missing'}</span>`).join('')}
async function load(){dashboard=await fetch('/api/dashboard').then(r=>r.json());render()}function render(){let s=dashboard.summary,fb=dashboard.facebook;$('#cards').innerHTML=`<div class=card><div class=number>${s.active_users}/${s.users}</div>Active users</div><div class=card><div class=number>${s.completed_runs}</div>Completed runs</div><div class=card><div class=number>${s.failed_runs}</div>Failed runs</div><div class=card><div class=number>${ms(s.observed_runtime_5h_ms.claude)}</div>Claude: observed 5h</div><div class=card><div class=number>${ms(s.observed_runtime_5h_ms.codex)}</div>Codex: observed 5h</div>`;$('#facebook-counts').textContent=`Received ${fb.received} · Replied ${fb.replied} · Failed ${fb.failed}`;$('#facebook-events').innerHTML=fb.events.length?fb.events.map(x=>`<tr><td>${time(x.timestamp)}</td><td>${esc(x.event)}</td><td><code>${esc(x.user_id)}</code><br>${esc(x.session||'')}</td><td class='${x.event==='facebook_agent_failed'?'bad':'ok'}'>${x.event==='facebook_agent_failed'?'Failed':'OK'}</td></tr>`).join(''):`<tr><td colspan=4 class=muted>No Facebook events yet.</td></tr>`;let q=$('#user').value.toLowerCase(),e=$('#engine').value;$('#users').innerHTML=dashboard.users.filter(x=>!q||`${x.name} ${x.user_id}`.toLowerCase().includes(q)).filter(x=>!e||x.engine===e||x.engines[e]).map(x=>`<tr><td><b>${esc(x.name)}</b><br><code>${esc(x.user_id)}</code> · ${esc(x.role)}</td><td class='${x.status==='active'?'ok':'bad'}'>${esc(x.status)}</td><td><b>${esc(label(x.engine))}</b><br>${esc(x.model)} · ${esc(x.effort)}</td><td>${esc(JSON.stringify(x.engines))}</td><td>${esc(x.failures)}</td><td>${esc(x.permissions.join(', ')||'—')}</td><td>${time(x.last_seen_at)}</td></tr>`).join('');$('#events').innerHTML=dashboard.events.filter(x=>!e||x.engine===e).map(x=>`<tr><td>${time(x.timestamp)}</td><td>${esc(x.user_id)}</td><td>${esc(x.event)}</td><td>${esc(label(x.engine||'—'))} ${esc(x.model||'')}<br>${esc(x.effort||'')}</td><td>${esc(x.session)}</td><td>${x.duration_ms?ms(x.duration_ms):'—'}</td></tr>`).join('')}
$('#user').oninput=render;$('#engine').onchange=render;$('#facebook').onsubmit=async e=>{e.preventDefault();let f=e.currentTarget,p=Object.fromEntries(new FormData(f));p.enabled=f.elements.enabled.checked;let r=await fetch('/api/facebook/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),x=await r.json();note(x.error||'Saved. Friday reads configuration immediately.');f.elements.app_secret.value=f.elements.page_access_token.value=f.elements.verify_token.value='';await loadFacebook()};$('#test-facebook').onclick=async()=>{note('Testing Graph API…');let r=await fetch('/api/facebook/test',{method:'POST'}),x=await r.json();note(x.error||`Connected: ${x.name||x.id||'OK'}`)};$('#generate-token').onclick=()=>{let r=crypto.getRandomValues(new Uint32Array(4));$('#facebook').elements.verify_token.value=[...r].map(v=>v.toString(36)).join('-');note('Token generated. Copy it, then save configuration.')};$('#copy-token').onclick=()=>copy($('#facebook').elements.verify_token.value);$('#copy-url').onclick=()=>copy(facebook.webhook_url||'');load();loadFacebook();setInterval(load,10000);
</script></body></html>"""
